package models

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type EventContext struct {
	WorkCenterCode   *string    `json:"work_center_code,omitempty"`
	LocationID       *uuid.UUID `json:"location_id,omitempty"`
	Reason           *string    `json:"reason,omitempty"`
	ExternalRef      *string    `json:"external_ref,omitempty"`
	CorrectionReason *string    `json:"correction_reason,omitempty"`
	SessionID        *uuid.UUID `json:"session_id,omitempty"` // 👈 new field
}

type EventMetadata struct {
	ShiftID         *uuid.UUID `json:"shift_id,omitempty"`
	ClassID         *uuid.UUID `json:"class_id,omitempty"`
	IsAutoGenerated *bool      `json:"is_auto_generated,omitempty"`
	IsCorrection    *bool      `json:"is_correction,omitempty"`
	OverrideStatus  *string    `json:"override_status,omitempty"`
	CorrectedBy     *uuid.UUID `json:"corrected_by,omitempty"`
}

type AttendanceEvent struct {
	AttendanceEventID uuid.UUID       `json:"attendance_event_id" db:"attendance_event_id"`
	CompanyID         uuid.UUID       `json:"company_id" db:"company_id"`
	SubjectType       string          `json:"subject_type" db:"subject_type"` // employee / student / customer
	SubjectID         uuid.UUID       `json:"subject_id" db:"subject_id"`
	EventType         string          `json:"event_type" db:"event_type"`
	EventTime         time.Time       `json:"event_time" db:"event_time"`
	SourceType        string          `json:"source_type" db:"source_type"`
	SourceID          *uuid.UUID      `json:"source_id,omitempty" db:"source_id"`
	DeviceID          *string         `json:"device_id,omitempty" db:"device_id"`
	DeviceUserCode    *string         `json:"device_user_code,omitempty" db:"device_user_code"`
	IPAddress         *string         `json:"ip_address,omitempty" db:"ip_address"`
	Context           EventContext    `json:"context" db:"context"`
	Metadata          EventMetadata   `json:"metadata" db:"metadata"`
	RawEventPayload   json.RawMessage `json:"raw_event_payload,omitempty" db:"raw_event_payload"`
	CreatedAt         time.Time       `json:"created_at" db:"created_at"`
	CreatedBy         *uuid.UUID      `json:"created_by,omitempty" db:"created_by"`
	EventDate         time.Time       `json:"event_date" db:"event_date"` // generated column
}
