package models

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// EventContext carries free-form metadata about the circumstances of a
// punch. Location is NOT stored here — it lives on the event itself as
// EmploymentLocationID and GeofenceID, so it can be indexed and queried.
type EventContext struct {
	WorkCenterCode   *string    `json:"work_center_code,omitempty"`
	Reason           *string    `json:"reason,omitempty"`
	ExternalRef      *string    `json:"external_ref,omitempty"`
	CorrectionReason *string    `json:"correction_reason,omitempty"`
	SessionID        *uuid.UUID `json:"session_id,omitempty"`
}

type EventMetadata struct {
	ShiftID         *uuid.UUID `json:"shift_id,omitempty"`
	ClassID         *uuid.UUID `json:"class_id,omitempty"`
	IsAutoGenerated *bool      `json:"is_auto_generated,omitempty"`
	IsCorrection    *bool      `json:"is_correction,omitempty"`
	OverrideStatus  *string    `json:"override_status,omitempty"`
	CorrectedBy     *uuid.UUID `json:"corrected_by,omitempty"`
}

// AttendanceEvent is the canonical attendance event row.
//
// # TIMEZONE MODEL
//
// EventTime is the absolute UTC instant. The business meaning of that
// instant — which local day it belongs to, at which offset — is captured
// by three columns filled at write time by the ingest pipeline. The
// resolution chain walks position → location → work center → company:
//
//	Position.LocationID           → Location.Timezone
//	Position.WorkCenterCode       → WorkCenter.Timezone
//	WorkCenter.LocationID         → Location.Timezone (fallback)
//	Company.DefaultTimezone       (last resort)
//
// Column semantics:
//
//	EventTZ             IANA name, e.g. 'Asia/Kolkata'. Snapshot on the row
//	                    so future config changes don't retroactively
//	                    rewrite history.
//
//	EventOffsetMinutes  DST-aware offset in minutes at EventTime for EventTZ.
//	                    +330 for IST, -240 for EDT, -300 for EST. Audit-only.
//	                    Never use for display.
//
//	EventDateLocal      Local business date (YYYY-MM-DD) computed as
//	                    (EventTime AT TIME ZONE EventTZ)::date.
//	                    Pre-computed and indexed — this is what every
//	                    "today's punches at location X" query filters on.
//
//	EventCountry        ISO-3166 alpha-2 code ('IN', 'US'), resolved from
//	                    locations.country. Used for tax-residency reports.
//
// Never compute a business date at read time. Never trust the client's
// device timezone. Never use the server's local timezone.
type AttendanceEvent struct {
	AttendanceEventID uuid.UUID `json:"attendance_event_id" db:"attendance_event_id"`
	CompanyID         uuid.UUID `json:"company_id" db:"company_id"`
	SubjectType       string    `json:"subject_type" db:"subject_type"` // employee / student / customer
	SubjectID         uuid.UUID `json:"subject_id" db:"subject_id"`
	EventType         string    `json:"event_type" db:"event_type"`
	EventTime         time.Time `json:"event_time" db:"event_time"`

	// ── Timezone columns (all required, populated at write time) ──────
	// IANA name, e.g. 'Asia/Kolkata'. Resolved via the chain:
	//   position.location → location.timezone
	//   position.work_center → work_center.timezone
	//   work_center.location → location.timezone
	//   company.default_timezone
	EventTZ string `json:"event_tz" db:"event_tz"`

	// DST-aware offset in minutes at EventTime for EventTZ.
	// +330 for IST, -240 for EDT, -300 for EST. Range: -720..840.
	EventOffsetMinutes int16 `json:"event_offset_minutes" db:"event_offset_minutes"`

	// Local business date in EventTZ. Pre-computed, indexed, immutable.
	EventDateLocal time.Time `json:"event_date_local" db:"event_date_local"`

	// Optional ISO-3166 alpha-2 code. Populated from locations.country.
	EventCountry *string `json:"event_country,omitempty" db:"event_country"`

	// Two location dimensions (snapshots)
	EmploymentLocationID *uuid.UUID `json:"employment_location_id,omitempty" db:"employment_location_id"`
	GeofenceID           *uuid.UUID `json:"geofence_id,omitempty" db:"geofence_id"`

	SourceType     string     `json:"source_type" db:"source_type"`
	SourceID       *uuid.UUID `json:"source_id,omitempty" db:"source_id"`
	DeviceID       *string    `json:"device_id,omitempty" db:"device_id"`
	DeviceUserCode *string    `json:"device_user_code,omitempty" db:"device_user_code"`
	IPAddress      *string    `json:"ip_address,omitempty" db:"ip_address"`

	Context         EventContext    `json:"context" db:"context"`
	Metadata        EventMetadata   `json:"metadata" db:"metadata"`
	RawEventPayload json.RawMessage `json:"raw_event_payload,omitempty" db:"raw_event_payload"`

	CreatedAt time.Time  `json:"created_at" db:"created_at"`
	CreatedBy *uuid.UUID `json:"created_by,omitempty" db:"created_by"`
}
