apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse                     
    type: grafana-clickhouse-datasource
    access: proxy

    isDefault: true
    editable: false

    jsonData:
      host: $CLICKHOUSE_HOST
      port: $CLICKHOUSE_HTTP_PORT
      protocol: http
      username: $CLICKHOUSE_USER
      defaultDatabase: $CLICKHOUSE_DATABASE
      tlsSkipVerify: false

    secureJsonData:
      password: $CLICKHOUSE_PASSWORD