apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy

    url: $ELASTICSEARCH_URL
    database: $ELASTICSEARCH_INDEX

    jsonData:
      timeField: created_at
      esVersion: $ELASTICSEARCH_VERSION
      interval: Daily

    secureJsonData:
      password: $ELASTICSEARCH_PASSWORD

    editable: false